# Generated by Django 4.2.25 on 2025-10-08 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("severity", models.CharField(db_index=True, max_length=20)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                ("client_ip", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("request_path", models.CharField(max_length=500)),
                ("request_method", models.CharField(max_length=10)),
                ("additional_data", models.JSONField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="audit_event_event_t_5f5939_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="audit_event_user_id_69236c_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="audit_event_severit_57fc6b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        help_text="Empreinte unique de l'appareil",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Date d'expiration de la confiance"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trusted_devices",
                "unique_together": {("user", "device_fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP (Time-based One-Time Password)"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("backup", "Backup Codes"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom donné par l'utilisateur", max_length=100
                    ),
                ),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_devices",
                "unique_together": {("user", "device_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code de sauvegarde à 8-10 caractères",
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_backup_codes",
                "unique_together": {("user", "code")},
            },
        ),
    ]
