# Generated by Django 4.2.13 on 2025-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditeventmodel",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditeventmodel",
            name="success",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
