# Generated by Django 4.2.25 on 2025-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
