# Generated by Django 4.2.25 on 2025-10-10 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogsettings_subscriber_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogsettings",
            name="enable_newsletter",
        ),
        migrations.RemoveField(
            model_name="blogsettings",
            name="seo_settings",
        ),
        migrations.RemoveField(
            model_name="blogsettings",
            name="social_links",
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 10, 10, 13, 39, 34, 489419, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom du category"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Créer le"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, max_length=500, verbose_name="Extrait"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
    ]
